name: Example Pipeline

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Compile program
        run: |
          g++ -std=c++11 negarr.cpp proxy.cpp testq1.cpp -o main

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: program
          path: main


  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download program
        uses: actions/download-artifact@v4
        with:
          name: program

      - name: Run test
        run: |
          chmod +x main
          ./main


  package:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Download program
        uses: actions/download-artifact@v4
        with:
          name: program

      - name: Create package
        run: |
          zip submission.zip *.cpp main

      - name: Upload package
        uses: actions/upload-artifact@v4
        with:
          name: submission
          path: submission.zip


  deploy:
    needs: package
    runs-on: ubuntu-latest

    steps:
      - name: Download package
        uses: actions/download-artifact@v4
        with:
          name: submission

      - name: Simulate deployment
        run: |
          echo "Deploying submission.zip..."
          ls -l
